Add OB as partner + remove emmanuel espias
green-code-initiative/ecoCode-website pull request #24
Opened 2024-06-06 20:15 UTC by glalloue

2024-06-06 21:32 UTC, utarwyn requested changes

2024-06-06 21:32 UTC, utarwyn commented on public/img/organizations/orange-business.webp
Can you resize this image to 160x55? (as described in [src/assets/data/partner-organizations.json](https://github.com/green-code-initiative/ecoCode-website/pull/24/files#diff-5f59b1ba4cd9685caf4aeef9494085887aa59d8850c9268fecf3f33956bb35fa))

2024-06-06 21:32 UTC, utarwyn commented on public/img/profil/jerome_cardon.webp
Can you resize this image to 80x80?

2024-06-07 07:36 UTC, glalloue commented on public/img/organizations/orange-business.webp
yes you're right, i'm going to do that ;)

2024-06-07 07:54 UTC, glalloue commented on public/img/organizations/orange-business.webp
image reisized

2024-06-07 07:54 UTC, glalloue commented on public/img/profil/jerome_cardon.webp
image resized

2024-06-07 08:08 UTC, utarwyn approved these changes
LGTM 💯 Thank you for the changes!

2024-06-07 08:42 UTC, merged