Fix rules form
green-code-initiative/ecoCode-website pull request #9
Opened 2023-10-09 11:03 UTC by BradleyDsx

2023-10-09 11:44 UTC, obeone commented on src/components/Shared/FormSecond.vue
>      return true;
Pourquoi des ifs/else ? (Cela vaut, à priori, pour tous les blocs modifiés)

2023-10-09 11:47 UTC, BradleyDsx commented on src/components/Shared/FormSecond.vue
>      return true;
Oui c'est vrais j'ai oublié de l'ai enlevé

2023-10-09 17:40 UTC, obeone requested changes

2023-10-09 17:40 UTC, obeone commented on src/components/Shared/Form.vue
>        }
Pourquoi le construire comme ça ? Autant mettre des `&&` non ?

2023-10-09 17:40 UTC, obeone commented on src/components/Shared/Form.vue
>    if (error.value || error.value || error.value || error.value) {
Gneh ?

2023-10-09 17:40 UTC, obeone commented on src/components/Shared/Form.vue
>    if (error.value || error.value || error.value || error.value) {
De plus, autant mettre un else avec la correction au dessus ?

2023-10-10 12:05 UTC, obeone approved these changes

2023-10-10 12:41 UTC, obeone commented
Commenter le code est une très bonne pratique !

par contre, on privilégiera en anglais (même si le site est en français, on va espérer une traduction un jour…), mais aussi, dans le cadre de classes, function etc, l’usage type de doc parsables par des outils (genre IDE). 
En JS, il y a https://jsdoc.app/about-getting-started.html

2023-10-11 09:36 UTC, merged